#ifndef MESSAGETYPEENUM_H
#define MESSAGETYPEENUM_H
enum MessageType
{
    LOGIN=0X01,
    REGIST,
    PRIVATE_MSG,
    GROUP_MSG,
    USER_QUERY,
    GROUP_QUERY,
    USER_STATUS,
    USER_INFO_UPDATE,
    SEND_MSG_PRIVATE,
    SEMD_MSG_GROUP,
    ADD_FRIEND,
    ADD_GROUP,
    CREATE_GROUP,
    HERT_BEATS,
    SELF_QUERY
};

#endif // MESSAGETYPEENUM_H
