#ifndef RESULTENUM_H
#define RESULTENUM_H

enum Result
{
    ACCOUNT_NOT_FOUND = 0X11,
    PASSWORD_ERROR,
    CONNECT_ERROR,
    LOGIN_SUCCESS,
    UPDATE_SUCCESS,
    UPDATE_FAIL,
    REGIST_SUCCESS,
    REGIST_FAIL,
    SURPLUS_OPRATION,
    HEARTBEATS
};

#endif // RESULTENUM_H
