#ifndef RESULTENUM_H
#define RESULTENUM_H

enum Result
{
    ACCOUNT_NOT_FOUND = 0X01,
    PASSWORD_ERROR,
    CONNECT_ERROR,
    LOGIN_SUCCESS,
    UPDATE_SUCCESS,
    UPDATE_FAIL,
    REGIST_SUCCESS,
    REGIST_FAIL
};

#endif // RESULTENUM_H
